// TypeScript types and interfaces for Smart Todo app
// Defines Task, Category, DailyContext, TaskSuggestion, AIAnalysis, and TaskAnalytics types

export interface Task {
  id: number;
  title: string;
  description: string;
  category?: number;
  category_name?: string;
  priority: 'low' | 'medium' | 'high' | 'urgent'; // Task priority levels
  status: 'pending' | 'in_progress' | 'completed' | 'cancelled'; // Task status
  deadline?: string;
  estimated_duration?: number;
  tags: string[];
  ai_priority_score: number; // AI-computed priority score
  ai_enhanced_description: string; // AI-generated description
  created_at: string;
  updated_at: string;
  completed_at?: string;
}

export interface Category {
  id: number;
  name: string;
  color: string;
  created_at: string;
}

// Represents a piece of daily context (e.g., message, note, meeting)
export interface DailyContext {
  id: number;
  content: string;
  context_type: 'whatsapp' | 'email' | 'note' | 'meeting' | 'call';
  timestamp: string;
  sender: string;
  subject: string;
  keywords: string[];
  sentiment_score: number;
  urgency_score: number;
  processed: boolean;
}

// Represents a task suggestion generated by AI
export interface TaskSuggestion {
  id: number;
  title: string;
  description: string;
  suggested_category: string;
  suggested_priority: string;
  suggested_deadline?: string;
  confidence_score: number;
  based_on_context?: number;
  created_at: string;
  accepted: boolean;
}

// Result of AI context analysis
export interface AIAnalysis {
  keywords: string[];
  sentiment_score: number;
  urgency_score: number;
  potential_tasks: string[];
  deadlines_mentioned: string[];
  people_mentioned: string[];
  projects_mentioned: string[];
}

// Analytics and insights for tasks
export interface TaskAnalytics {
  summary: {
    total_tasks: number;
    completed_tasks: number;
    pending_tasks: number;
    overdue_tasks: number;
    completion_rate: number;
  };
  priority_distribution: Record<string, number>;
  category_distribution: Record<string, number>;
  recent_tasks: Task[];
  ai_insights: {
    avg_priority_score: number;
    high_priority_tasks: number;
  };
} 