# Generated by Django 4.2.7 on 2025-07-05 12:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='DailyContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('context_type', models.CharField(choices=[('whatsapp', 'WhatsApp Message'), ('email', 'Email'), ('note', 'Personal Note'), ('meeting', 'Meeting'), ('call', 'Phone Call')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('urgency_score', models.FloatField(default=0.0)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TaskSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('suggested_category', models.CharField(max_length=100)),
                ('suggested_priority', models.CharField(max_length=10)),
                ('suggested_deadline', models.DateTimeField(blank=True, null=True)),
                ('confidence_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('based_on_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.dailycontext')),
            ],
            options={
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration', models.IntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('ai_priority_score', models.FloatField(default=0.0)),
                ('ai_enhanced_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.category')),
            ],
            options={
                'ordering': ['-ai_priority_score', '-created_at'],
            },
        ),
    ]
